// AUTO-GENERATED by scripts/gen-compat-routes.mjs — do not edit.
// 69 mock route modules run unchanged inside NestJS (R5.1 compat layer); 47 are native.
/* eslint-disable */
import * as m0 from "@/app/api/v1/accounting/accounts/route"
import * as m1 from "@/app/api/v1/accounting/accounts/[id]/route"
import * as m2 from "@/app/api/v1/accounting/config/route"
import * as m3 from "@/app/api/v1/accounting/open-invoices/route"
import * as m4 from "@/app/api/v1/accounting/payments/route"
import * as m5 from "@/app/api/v1/accounting/payments/[id]/route"
import * as m6 from "@/app/api/v1/accounting/receipts/route"
import * as m7 from "@/app/api/v1/accounting/receipts/[id]/route"
import * as m8 from "@/app/api/v1/accounting/statement/route"
import * as m9 from "@/app/api/v1/dashboard/route"
import * as m10 from "@/app/api/v1/import/route"
import * as m11 from "@/app/api/v1/items/[id]/ledger/route"
import * as m12 from "@/app/api/v1/mushak/[form]/route"
import * as m13 from "@/app/api/v1/notifications/route"
import * as m14 from "@/app/api/v1/notifications/read/route"
import * as m15 from "@/app/api/v1/opening-stock/route"
import * as m16 from "@/app/api/v1/opening-stock/[id]/route"
import * as m17 from "@/app/api/v1/production/batches/route"
import * as m18 from "@/app/api/v1/production/batches/[id]/route"
import * as m19 from "@/app/api/v1/production/batches/[id]/receive/route"
import * as m20 from "@/app/api/v1/production/boms/route"
import * as m21 from "@/app/api/v1/production/boms/[id]/route"
import * as m22 from "@/app/api/v1/production/config/route"
import * as m23 from "@/app/api/v1/production/lots/route"
import * as m24 from "@/app/api/v1/production/subcontract/route"
import * as m25 from "@/app/api/v1/production/work-orders/route"
import * as m26 from "@/app/api/v1/production/work-orders/[id]/route"
import * as m27 from "@/app/api/v1/sale-services/route"
import * as m28 from "@/app/api/v1/search/route"
import * as m29 from "@/app/api/v1/services/route"
import * as m30 from "@/app/api/v1/stock/route"
import * as m31 from "@/app/api/v1/vat/adjustments/route"
import * as m32 from "@/app/api/v1/vat/adjustments/[id]/route"
import * as m33 from "@/app/api/v1/vat/bond/route"
import * as m34 from "@/app/api/v1/vat/bond-uds/route"
import * as m35 from "@/app/api/v1/vat/bond-uds/[id]/route"
import * as m36 from "@/app/api/v1/vat/bond-uds/[id]/settle/route"
import * as m37 from "@/app/api/v1/vat/compliance/route"
import * as m38 from "@/app/api/v1/vat/drawback-claims/route"
import * as m39 from "@/app/api/v1/vat/drawback-claims/[id]/route"
import * as m40 from "@/app/api/v1/vat/drawback-claims/[id]/action/route"
import * as m41 from "@/app/api/v1/vat/exports/route"
import * as m42 from "@/app/api/v1/vat/late-filings/route"
import * as m43 from "@/app/api/v1/vat/late-filings/[id]/route"
import * as m44 from "@/app/api/v1/vat/late-filings/[id]/action/route"
import * as m45 from "@/app/api/v1/vat/penalty/route"
import * as m46 from "@/app/api/v1/vat/periods/route"
import * as m47 from "@/app/api/v1/vat/proceeds/route"
import * as m48 from "@/app/api/v1/vat/proceeds/batches/route"
import * as m49 from "@/app/api/v1/vat/proceeds/batches/[id]/route"
import * as m50 from "@/app/api/v1/vat/proceeds/batches/[id]/reverse/route"
import * as m51 from "@/app/api/v1/vat/proceeds/match/route"
import * as m52 from "@/app/api/v1/vat/proceeds/sample/route"
import * as m53 from "@/app/api/v1/vat/return-amendments/route"
import * as m54 from "@/app/api/v1/vat/return-amendments/[id]/route"
import * as m55 from "@/app/api/v1/vat/return-amendments/[id]/action/route"
import * as m56 from "@/app/api/v1/vat/returns/route"
import * as m57 from "@/app/api/v1/vat/returns/[period]/route"
import * as m58 from "@/app/api/v1/vat/returns/[period]/notes/[note]/route"
import * as m59 from "@/app/api/v1/vat/sd-eligible/route"
import * as m60 from "@/app/api/v1/vat/settings/route"
import * as m61 from "@/app/api/v1/vat/treasury/route"
import * as m62 from "@/app/api/v1/vat/treasury/[id]/route"
import * as m63 from "@/app/api/v1/vat/uds/route"
import * as m64 from "@/app/api/v1/vat/uds/[id]/route"
import * as m65 from "@/app/api/v1/vat/uds/fit/route"
import * as m66 from "@/app/api/v1/vat/vds/route"
import * as m67 from "@/app/api/v1/vat/vds/[id]/route"
import * as m68 from "@/app/api/v1/vat/vds/eligible/route"

export const routeModules: [string, Record<string, unknown>][] = [
  ["accounting/accounts", m0],
  ["accounting/accounts/[id]", m1],
  ["accounting/config", m2],
  ["accounting/open-invoices", m3],
  ["accounting/payments", m4],
  ["accounting/payments/[id]", m5],
  ["accounting/receipts", m6],
  ["accounting/receipts/[id]", m7],
  ["accounting/statement", m8],
  ["dashboard", m9],
  ["import", m10],
  ["items/[id]/ledger", m11],
  ["mushak/[form]", m12],
  ["notifications", m13],
  ["notifications/read", m14],
  ["opening-stock", m15],
  ["opening-stock/[id]", m16],
  ["production/batches", m17],
  ["production/batches/[id]", m18],
  ["production/batches/[id]/receive", m19],
  ["production/boms", m20],
  ["production/boms/[id]", m21],
  ["production/config", m22],
  ["production/lots", m23],
  ["production/subcontract", m24],
  ["production/work-orders", m25],
  ["production/work-orders/[id]", m26],
  ["sale-services", m27],
  ["search", m28],
  ["services", m29],
  ["stock", m30],
  ["vat/adjustments", m31],
  ["vat/adjustments/[id]", m32],
  ["vat/bond", m33],
  ["vat/bond-uds", m34],
  ["vat/bond-uds/[id]", m35],
  ["vat/bond-uds/[id]/settle", m36],
  ["vat/compliance", m37],
  ["vat/drawback-claims", m38],
  ["vat/drawback-claims/[id]", m39],
  ["vat/drawback-claims/[id]/action", m40],
  ["vat/exports", m41],
  ["vat/late-filings", m42],
  ["vat/late-filings/[id]", m43],
  ["vat/late-filings/[id]/action", m44],
  ["vat/penalty", m45],
  ["vat/periods", m46],
  ["vat/proceeds", m47],
  ["vat/proceeds/batches", m48],
  ["vat/proceeds/batches/[id]", m49],
  ["vat/proceeds/batches/[id]/reverse", m50],
  ["vat/proceeds/match", m51],
  ["vat/proceeds/sample", m52],
  ["vat/return-amendments", m53],
  ["vat/return-amendments/[id]", m54],
  ["vat/return-amendments/[id]/action", m55],
  ["vat/returns", m56],
  ["vat/returns/[period]", m57],
  ["vat/returns/[period]/notes/[note]", m58],
  ["vat/sd-eligible", m59],
  ["vat/settings", m60],
  ["vat/treasury", m61],
  ["vat/treasury/[id]", m62],
  ["vat/uds", m63],
  ["vat/uds/[id]", m64],
  ["vat/uds/fit", m65],
  ["vat/vds", m66],
  ["vat/vds/[id]", m67],
  ["vat/vds/eligible", m68],
]
