CREATE TABLE "purchase_lines" (
	"purchase_id" text NOT NULL,
	"ord" integer NOT NULL,
	"item_id" text NOT NULL,
	"name" text NOT NULL,
	"hs_code" text NOT NULL,
	"uom" text NOT NULL,
	"qty" numeric(18, 3) NOT NULL,
	"price" numeric(18, 2) NOT NULL,
	"sd_rate" numeric(7, 2) NOT NULL,
	"vat_rate" numeric(7, 2) NOT NULL,
	"subtotal" numeric(18, 2) NOT NULL,
	"sd" numeric(18, 2) NOT NULL,
	"vat" numeric(18, 2) NOT NULL,
	"total" numeric(18, 2) NOT NULL,
	"rebateable" boolean,
	"vds" boolean,
	"tti" numeric(18, 2),
	"duty_usd" numeric(18, 2),
	"duty_usd_rate" numeric(18, 6),
	"duty_av" numeric(18, 2),
	"duty_cd_rate" numeric(7, 2),
	"duty_cd" numeric(18, 2),
	"duty_rd_rate" numeric(7, 2),
	"duty_rd" numeric(18, 2),
	"duty_ait_rate" numeric(7, 2),
	"duty_ait" numeric(18, 2),
	"duty_at_rate" numeric(7, 2),
	"duty_at" numeric(18, 2),
	"foregone_cd" numeric(18, 2),
	"foregone_rd" numeric(18, 2),
	"foregone_sd" numeric(18, 2),
	"foregone_vat" numeric(18, 2),
	"foregone_ait" numeric(18, 2),
	"foregone_at" numeric(18, 2),
	"foregone_total" numeric(18, 2),
	CONSTRAINT "purchase_lines_purchase_id_ord_pk" PRIMARY KEY("purchase_id","ord"),
	CONSTRAINT "purchase_lines_duty_check" CHECK (("purchase_lines"."duty_av" is null and "purchase_lines"."duty_cd" is null) or ("purchase_lines"."duty_av" is not null and "purchase_lines"."duty_cd" is not null)),
	CONSTRAINT "purchase_lines_foregone_check" CHECK ("purchase_lines"."foregone_total" is null or "purchase_lines"."duty_av" is not null)
);
--> statement-breakpoint
CREATE TABLE "purchases" (
	"id" text PRIMARY KEY NOT NULL,
	"ord" serial NOT NULL,
	"invoice_no" text NOT NULL,
	"challan_no" text NOT NULL,
	"challan_date" date NOT NULL,
	"issue_date" date NOT NULL,
	"process" text NOT NULL,
	"category" text,
	"branch_id" text NOT NULL,
	"branch_name" text NOT NULL,
	"vendor_id" text NOT NULL,
	"vendor_name" text NOT NULL,
	"vendor_bin" text NOT NULL,
	"vendor_address" text NOT NULL,
	"mode" text NOT NULL,
	"method" text NOT NULL,
	"subtotal" numeric(18, 2) NOT NULL,
	"sd" numeric(18, 2) NOT NULL,
	"vat" numeric(18, 2) NOT NULL,
	"discount" numeric(18, 2) NOT NULL,
	"net_total" numeric(18, 2) NOT NULL,
	"paid" numeric(18, 2) NOT NULL,
	"due" numeric(18, 2) NOT NULL,
	"tti" numeric(18, 2) NOT NULL,
	"rebate" numeric(18, 2) NOT NULL,
	"issued_by" text NOT NULL,
	"designation" text NOT NULL,
	"narration" text,
	"created_at" timestamp (3) with time zone NOT NULL,
	"updated_at" timestamp (3) with time zone,
	"cancel_reason" text,
	"history" jsonb,
	"deleted_at" timestamp (3) with time zone,
	"boe_no" text,
	"boe_date" date,
	"boe_lc_no" text,
	"boe_lc_date" date,
	"boe_customs_house" text,
	"boe_origin" text,
	"boe_cnf_firm" text,
	"boe_receive_address" text,
	"boe_bonded" boolean,
	"boe_ud_no" text,
	CONSTRAINT "purchases_process_check" CHECK ("purchases"."process" in ('Created','Approved','Cancelled')),
	CONSTRAINT "purchases_category_check" CHECK ("purchases"."category" is null or "purchases"."category" in ('goods','service')),
	CONSTRAINT "purchases_mode_check" CHECK ("purchases"."mode" in ('Local','Foreign','Non-registered')),
	CONSTRAINT "purchases_method_check" CHECK ("purchases"."method" in ('Bank','Cash','Cheque','Mobile','Transaction')),
	CONSTRAINT "purchases_boe_check" CHECK (("purchases"."boe_no" is null and "purchases"."boe_lc_no" is null) or ("purchases"."boe_no" is not null and "purchases"."boe_lc_no" is not null)),
	CONSTRAINT "purchases_boe_bonded_check" CHECK ("purchases"."boe_bonded" is null or "purchases"."boe_no" is not null),
	CONSTRAINT "purchases_boe_ud_check" CHECK ("purchases"."boe_ud_no" is null or "purchases"."boe_bonded" is true)
);
--> statement-breakpoint
CREATE INDEX "purchase_lines_item_idx" ON "purchase_lines" USING btree ("item_id");--> statement-breakpoint
CREATE UNIQUE INDEX "purchases_invoice_no_key" ON "purchases" USING btree ("invoice_no");--> statement-breakpoint
CREATE INDEX "purchases_live_idx" ON "purchases" USING btree ("created_at") WHERE "purchases"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "purchases_issue_date_idx" ON "purchases" USING btree ("issue_date");--> statement-breakpoint
CREATE INDEX "purchases_vendor_idx" ON "purchases" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "purchases_branch_idx" ON "purchases" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "purchases_boe_bonded_idx" ON "purchases" USING btree ("boe_no") WHERE "purchases"."boe_bonded" is true;